### ISSUE TITLE
Machine with Modifiers do not form because modifiers are direction dependent

### ISSUE THREAD

**Issue by jchung01** [KasumiNova/ModularMachinery-Community-Edition#12]
Usually when building a modular machine, you can orient the whole structure in any direction (North, South, East, West) and it forms correctly, regardless of how the json is defined. However, modifiers that are defined in the json are direction dependent. For example, if you have this modifier:
```
"modifiers": [
        {
            "elements": "minecraft:diamond_block",
            "x": 0,
            "y": 3,
            "z": 1,
            "description": "Multiplies amounts processed by 4",
            "modifiers": [{
                "io": "output",
                "target": "modularmachinery:item",
                "operation": 1,
                "multiplier": 4
            },
            {
                "io": "input",
                "target": "modularmachinery:item",
                "operation": 1,
                "multiplier": 4
            }]
        }
],
```
This will only allow the machine to form when building the modular machine oriented to the south direction (because south is the positive-z direction). This issue does not exist in the original version of MM.

**Comment by KasumiNova** [comment]
Please provide the mod version used, if it is not the latest version, try to update to the latest version. If the problem persists, I try to reproduce it.

**Comment by jchung01** [comment]
Using latest version (r30). Here's a test script, renamed as .json for it to work of course (ignore the name, just copied from a pack as a template):
[gaia_altar.json.txt](https://github.com/KasumiNova/ModularMachinery-Community-Edition/files/11245684/gaia_altar.json.txt).
Assembling it with a diamond block instead of a gold block with structure facing:
- South: forms correctly
- Any other direction: does not form

**Comment by KasumiNova** [comment]
I have submitted a commit that may fix this issue, and it works fine in my tests, you can download it from the latest Github Actions build and test it.

**Comment by jchung01** [comment]
Tested the build in my world with a lot of compact machines, seems to be working now, thanks!

**Comment by KasumiNova** [comment]
Thanks for the feedback, I will find time to release this version of the mod.
