### ISSUE TITLE
Add New Controller Textures, en_us,  新しいコントローラー テクスチャを追加する, en_jp

### ISSUE THREAD

**Issue by BLocky104** [KasumiNova/ModularMachinery-Community-Edition#15]
Make it Possible to add custom controller Textures, en_us. カスタム コントローラー テクスチャを追加できるようにする
, en_jp

**Comment by KasumiNova** [comment]
Each machine has its own controller, and you can customize their materials after installing ResouceLoader.
at `resources/modularmachinery/blockstates/`
