### ISSUE TITLE
Preview not showing

### ISSUE THREAD

**Issue by BLocky104** [KasumiNova/ModularMachinery-Community-Edition#16]
Upon creating a Multiblock, the Modular machinery multiblock preview does not show
創建多塊後，模塊化機械多塊預覽不顯示

**Comment by KasumiNova** [comment]
How did you create the multiblock structure?
I need more information to be able to locate the problem.

**Comment by KasumiNova** [comment]
Sorry, as the information I obtained could not determine that it was a mod problem, this issue has been closed, please reopen it if you have new information.

**Comment by BLocky104** [comment]
also i have figured out the problem, upon accidentaly mods.jei.JEI.removeAndHide, the normal controller none of the other controllers textures
