### ISSUE TITLE
setTag() not working properly | NBT标签匹配方法失效

### ISSUE THREAD

**Issue by ccpemily** [KasumiNova/ModularMachinery-Community-Edition#2]
MMCE提供的RecipePrimer.setTag(NBTCompound compound)方法不能正常工作

具体bug：
使用以下方法
setTag({Configuration: 0})（CT2Tag）
setTag("{Configuration: 0}")
setTag("{\"Configuration\": \"0\"}")（原版NBT写法）
setTag("{\"Configuration\": \"==0\"}")（教程中的NBT匹配）
setTag("{\"Configuration\": \"<1\"}")
均不能匹配具有NBT标签{"Configuration": "0"}的编程电路，放入具有任何Configuration值的编程电路机器都会按照配置为0的配方工作。同样地，当把具有NBT标签的物品作为输出时，setTag也不能正确地写入NBT标签，除非使用CT2的IItemStack.withTag(TagCompound tag)方法。

**Comment by KasumiNova** [comment]
Fixed on 1.11.1-r11.
