### ISSUE TITLE
tinkers construct

### ISSUE THREAD

**Issue by Tiamu322** [KasumiNova/ModularMachinery-Community-Edition#21]
The new version of the mod requires updating tinkers construct. Is it possible to make it so that it would not need to be updated?
![image](https://github.com/KasumiNova/ModularMachinery-Community-Edition/assets/125770260/ae3b5899-7e2e-4c05-b487-1bf2ea8e8552)

**Comment by KasumiNova** [comment]
To be honest, I don't think anyone would use an outdated mod that hasn't been updated in almost 3 years...

**Comment by Tiamu322** [comment]
We do not update the mod on the server, so as not to lose numerous fixes, duplicates. Anyway, thanks.

**Comment by KasumiNova** [comment]
Consider compatibility in R39.

**Comment by mczph** [comment]
Actually, I'm curious about your fixes on this Tinkers' Construct 2 version,maybe I can help you with that so you can update it.

**Comment by Tiamu322** [comment]
Unfortunately, my problem has not been solved, I will be very glad if you correct it in the future

![image](https://github.com/KasumiNova/ModularMachinery-Community-Edition/assets/125770260/85ff1b68-e2fa-4e86-8810-c95b0d3e57be)
