### ISSUE TITLE
Textures

### ISSUE THREAD

**Issue by BLocky104** [KasumiNova/ModularMachinery-Community-Edition#22]
where are the controller textures stored? is there any way to add new textures for them with ressource loader?
(for 1 particular controller)

**Comment by KasumiNova** [comment]
See #15
Machine Example: resources/modularmachinery/blockstates/xxx_controller.json
Factory Example: resources/modularmachinery/blockstates/xxx_factory_controller.json

**Comment by BLocky104** [comment]
sorry for the late response, havent checked my github for a wile
but where is the .png stored, not the blockstate?

**Comment by KasumiNova** [comment]
Defined by you.
Please refer to the default blockstates file for location definitions.

**Comment by KasumiNova** [comment]
This issue has been closed for a long time without a response.
If there is a new issue, please reopen it.
