### ISSUE TITLE
Invetory Item

### ISSUE THREAD

**Issue by RenanVieira88** [KasumiNova/ModularMachinery-Community-Edition#23]
Good day everyone,

Inventory Item always looks like controler:

![issue](https://github.com/KasumiNova/ModularMachinery-Community-Edition/assets/24437327/84014618-20e2-40d4-93eb-790d722f3c21)

In blockstate:
`{
  "forge_marker": 1,
  "defaults": {
    "model": "modularmachinery:rubberextractor_controller"
  },
  "variants": {
    "facing=north": {
      "model": "modularmachinery:rubberextractor_controller"
    },
    "facing=south": {
      "model": "modularmachinery:rubberextractor_controller",
      "y": 180
    },
    "facing=west": {
      "model": "modularmachinery:rubberextractor_controller",
      "y": 270
    },
    "facing=east": {
      "model": "modularmachinery:rubberextractor_controller",
      "y": 90
    }  
  }
}
`

Model:

`{
    "parent": "modularmachinery:block/blockmodel_overlay_orientable_all_TEST",
    "textures": {
        "bg_all": "modularmachinery:blocks/rub_ext/machine_bronze_plated_bricks",
        "ov_top": "modularmachinery:blocks/rub_ext/overlay_top",
        "ov_side": "modularmachinery:blocks/rub_ext/overlay_side",
        "ov_front": "modularmachinery:blocks/rub_ext/overlay_front"
    }
}
`

Item Model:

`{
    "parent": "modularmachinery:block/rubberextractor_controller"
}
`

**Comment by KasumiNova** [comment]
Mod Version?

**Comment by RenanVieira88** [comment]
Nervermind, in newest version its solved
