### ISSUE TITLE
[Suggestion] Add fixed times to consume item

### ISSUE THREAD

**Issue by RenanVieira88** [KasumiNova/ModularMachinery-Community-Edition#25]
A exemple:

{
            "type": "item",
            "io-type": "input",
            "item": "contenttweaker:random_item",
            "amount": 1,
            "TimesRecipeMustBeExecutedToConsume": 1600
        },

In this exemple, the Recipe must be executed (with results) 1600 to get consume the input Item

**Comment by KasumiNova** [comment]
Nice idea, consider added in R40.

**Comment by RenanVieira88** [comment]
That's a great news

My workaroud for now is:

`{
       "machine": "fission",
    "registryName": "uranium",
    "recipeTime": 4,
    "requirements": [
        {
            "type": "item",
			"io-type": "input",
			"item": "contenttweaker:cell_uranium",
			"chance": 0.0001
        },
        {
            "type": "fluid",
            "io-type": "input",
            "fluid": "coolant",
            "amount": 400
        },
        {
            "type": "fluid",
            "io-type": "output",
            "fluid": "hot_coolant",
            "amount": 400
        },
		{
            "type": "item",
			"io-type": "output",
			"item": "contenttweaker:cell_uranium_depleded",
			"chance": 0.0001
        }
    ]
}`

So the main idea is:
Uranium rod has consumed > after 4 ticks the machine spells 400mb of hot coolant and consume 400mb of coolant

It would be nice to put the uranium to be consumed at the beginning of the recipe, during the determined time (in this case 1600 ticks) it would continue consuming the 400mb of coolant every 4 ticks but not the uranium, and at the end of the 1600 ticks it would give an item like depleted uranium

Not sure if I

**Comment by KasumiNova** [comment]
If you use ZenScript to write recipes, you can use `addFluidPerTickInput(<liquid:xxx>)` to make each Tick consume fluid.

**Comment by RenanVieira88** [comment]
Hi, I've try this:

`val uranim = mods.modularmachinery.RecipeBuilder.newBuilder("uranim", "fision", 200, 0);

uranim.addFluidPerTickInput(<liquid:coolant>);
uranim.addFluidPerTickOutput(<liquid:hot_coolant>);
uranim.addItemInput(<contenttweaker:cell_uranium>);
uranim.addItemOutput(<contenttweaker:cell_uranium_depleded>);

uranim.build();`

Also add *400 to fluids, but does't work, I did something wrong?

**Comment by RenanVieira88** [comment]
Nevermind, I've write the name of machine wrong.... :D

Works great!!!!!!!!!
