### ISSUE TITLE
更新至新版本后，服务端崩溃

### ISSUE THREAD

**Issue by ProperSAMA** [KasumiNova/ModularMachinery-Community-Edition#26]
如题，将 ModularMachinery-CE-1.12.2-1.11.1-r29 更新至 r39

更新后，进入部分包含模块化机械的区域后，服务端无响应，但没有彻底崩溃，也没有crash-report
若退回mod版本至r29，则不会再出现这种情况

服务端Log：https://pastebin.com/UtH3D80U

**Comment by KasumiNova** [comment]
使用 Github Actions 的构建时是否有这个问题？
https://github.com/KasumiNova/ModularMachinery-Community-Edition/actions/runs/5166902529

**Comment by ProperSAMA** [comment]
感谢回复，使用这个版本后，不再出现无响应的问题了

我该直接在正式环境使用这个版本，还是该等它在CurseForge发布？

**Comment by KasumiNova** [comment]
近期会发布新版本，还请耐心等待。
