### ISSUE TITLE
与Storage Drawers共同使用时，物品输入仓堆叠数量异常

### ISSUE THREAD

**Issue by ProperSAMA** [KasumiNova/ModularMachinery-Community-Edition#27]
在社区版中，物品输入仓可以自动从邻近的容器中抽取物品，这个效果在原版箱子上一切正常
但如果把[Storage Drawers Mod](https://www.mcmod.cn/class/408.html)的抽屉放在物品输入仓旁边，会出现以下异常：

在单机模式下，堆叠数量会超出上限
<img width="392" alt="单机-超量堆叠" src="https://github.com/KasumiNova/ModularMachinery-Community-Edition/assets/44425354/6e920985-27f1-4ccb-beca-ab9b72fa05aa">

在服务器中，物品会消失
<img width="397" alt="服务器-物品消失" src="https://github.com/KasumiNova/ModularMachinery-Community-Edition/assets/44425354/1c072618-50b4-41d7-9d03-6bed7c53093d">

如果破坏这个物品输入仓，消失的物品会掉出来
<img width="1037" alt="服务器-物品掉落" src="https://github.com/KasumiNova/ModularMachinery-Community-Edition/assets/44425354/c3c939b3-6b9d-4808-ad7e-a339b9bd05d2">

**Comment by KasumiNova** [comment]
找到问题所在了，会在下一个版本中修复。
