### ISSUE TITLE
Ohh Tinkers

### ISSUE THREAD

**Issue by Tiamu322** [KasumiNova/ModularMachinery-Community-Edition#28]
Unfortunately, my problem has not been solved, I will be very glad if you correct it in the future
![image](https://github.com/KasumiNova/ModularMachinery-Community-Edition/assets/125770260/ee051532-889b-4455-9a34-4b469403663a)

**Comment by KasumiNova** [comment]
Ahh...

**Comment by Tiamu322** [comment]
Thank you very much. In version 41, everything works.

**Comment by KasumiNova** [comment]
Fixed in R41.
