### ISSUE TITLE
Parameter error in CraftTweaker2 event system | 机器事件系统传参问题

### ISSUE THREAD

**Issue by ccpemily** [KasumiNova/ModularMachinery-Community-Edition#3]
Method: all event register method in .../crafttweaker/event/MMEvents.java

Bug:
parameter in zs is "registry_name", but in console it is "moduarmachinery:registry_name" (as the param machineRegistryName), which always cause a "Cloud not found machine 'registry_name'" Error, since the registry name parsed in is such as this: "modularmachinery:modularmachinery:registry_name"

**Comment by KasumiNova** [comment]
Fixed on 1.11.1-r11.
