### ISSUE TITLE
[crash] server crash with voids backpack and mmce

### ISSUE THREAD

**Issue by Xplodin** [KasumiNova/ModularMachinery-Community-Edition#32]
https://gist.github.com/Xplodin/fa2ad70208820feaf9c91eb3160d284a

server crashes on startup

**Comment by KasumiNova** [comment]
Can you provide a copy of the mod? I can't find a file for this.

**Comment by Xplodin** [comment]
yes sorry its 1.12.2 and its https://www.curseforge.com/minecraft/mc-mods/v0ids-smart-backpacks

**Comment by KasumiNova** [comment]
I blame this problem on V0id's Smart Backpacks mod (https://github.com/V0idWa1k3r/SmartBackpacks/issues/23).
It uses horrible methods to achieve functionality.

Consider adding this mod for targeted compatibility in the R42 version.

**Comment by KasumiNova** [comment]
I rechecked the history of this mod and it has a fix submitted in 2019 for this issue, but it wasn't posted on CurseForge.
