### ISSUE TITLE
服务端报错

### ISSUE THREAD

**Issue by ProperSAMA** [KasumiNova/ModularMachinery-Community-Edition#34]
模组版本：ModularMachinery-CE-1.12.2-1.11.1-r40

报错内容如下：
https://pastebin.com/xf6HGqCM
只摘取了一部分，重复的报错刷了很多，一上午能刷200~600M的日志

暂时不清楚触发原因和造成的影响

**Comment by ProperSAMA** [comment]
经过进一步测试，基本掌握了该报错的触发方法：

原理基本与[这个issues](https://github.com/KasumiNova/ModularMachinery-Community-Edition/issues/29#issuecomment-1592408029)相同

机器正在工作时更换方块，将一个机器改变为另一个机器，配方不会停止，会继续运行并输出产物，且不会消耗材料
配方完成时，会输出这个报错

该报错会导致玩家无需消耗材料即可持续获得产物，较严重

在[之前的issues](https://github.com/KasumiNova/ModularMachinery-Community-Edition/issues/29#issuecomment-1597909257)中，您曾提到
> 原版mm在加载存档的时候有概率丢失机械的配方，因为结构可能跨区块。
mmce当初为了解决这个问题临时让配方不再消失，虽然后来有其他方法修了这个问题，不过一直没加上。
r41考虑修复。

r41是否会同时修复这个报错？预计将在什么时候发布？

**Comment by KasumiNova** [comment]
https://github.com/KasumiNova/ModularMachinery-Community-Edition/issues/29#issuecomment-1597909257

这个问题被修复的时候应该会同时被修复。

最近应该会发布一个版本，然后可能会停更一段时间（最近充裕时间不是很多）。

**Comment by ProperSAMA** [comment]
更新至r41版本后，拆除方块会清空 `activeRecipe`，无法让新搭建的机器触发这个报错了

但似乎因为需要拆除才会清空，只要不拆除r40已经报错的机器，换成r41后就仍会报错

报错不包含坐标等信息，人工检查玩家的每一台机器也不太现实
是否能在触发此报错时清除报错机器的`activeRecipe`，或通过其他方式阻止这个报错？

**Comment by KasumiNova** [comment]
😨

**Comment by KasumiNova** [comment]
🤔
有时间小看一眼，可以留个联系方式吗，github issue 不是经常看

**Comment by ProperSAMA** [comment]
> 🤔 有时间小看一眼，可以留个联系方式吗，github issue 不是经常看

QQ：997794945
