### ISSUE TITLE
Add an "ME Output Bus" that replaces the output hatch

### ISSUE THREAD

**Issue by SweptWasTaken** [KasumiNova/ModularMachinery-Community-Edition#35]
In GregTech, they have a block called the "ME Output Bus", which directly ejects any multiblocks items directly to a connected ME network. This is better for performance and organization.

https://github.com/GTNewHorizons/GT5-Unofficial/blob/master/src/main/java/gregtech/common/tileentities/machines/GT_MetaTileEntity_Hatch_OutputBus_ME.java

**Comment by KasumiNova** [comment]
WIP :)

**Comment by KasumiNova** [comment]
Completed at version R44.
