### ISSUE TITLE
MachineUpgradeHelper.addFixedUpgrade(item,string)不识别metadata

### ISSUE THREAD

**Issue by Sam-0324** [KasumiNova/ModularMachinery-Community-Edition#37]
如题。
版本：1.11.1-r43
> 原代码：
MachineUpgradeHelper.addFixedUpgrade(<item:minecraft:dye:4>,"ic2_speed");
升级已注册。

实际效果：所有物品id为minecraft:dye的物品均被认定为"ic2_speed"升级。

**Comment by KasumiNova** [comment]
是已知问题，考虑在未来修复。
