### ISSUE TITLE
Modular Diversity cannot run with MMCE

### ISSUE THREAD

**Issue by SieIin** [KasumiNova/ModularMachinery-Community-Edition#5]
https://gist.github.com/SieIin/4c5759c48fae2531c78ed92a83fce1a9

same as original MM, even CE cannot run with it

**Comment by KasumiNova** [comment]
Sorry, but since MMCE is based on version 1.11.1, the original Modular Diversity is not compatible with 1.11.1.

**Comment by SieIin** [comment]
sad news. understanded.
