### ISSUE TITLE
Status text in controller isn't updating properly

### ISSUE THREAD

**Issue by FakeDomi** [KasumiNova/ModularMachinery-Community-Edition#6]
- It says "missing structure" after successfully forming a multiblock
- When breaking a structure that has already done work before, it still says "missing inputs"
- Also happens with missing power, no space to output etc.

The status text in The One Probe is updated correctly.

**Comment by KasumiNova** [comment]
Maybe I broke some mechanism when I tried to optimize the controller update frequency, I will try to fix it if this problem will have a bigger impact on the controller.
A similar question as to why the controller update frequency needs to be optimized is worth considering here：https://github.com/HellFirePvP/ModularMachinery/issues/228

**Comment by FakeDomi** [comment]
![image](https://user-images.githubusercontent.com/1492543/223469012-ba69444b-ed22-4070-8305-e61701a582c0.png)

**Comment by KasumiNova** [comment]
It should be a good idea to update the controller when the player opens the controller interface.

**Comment by KasumiNova** [comment]
You can try using this build of Actions, which should have fixed this problem.
https://github.com/KasumiNova/ModularMachinery-Community-Edition/actions/runs/4355967426

**Comment by FakeDomi** [comment]
It only updates once when opening the controller gui but that's good enough for me. 👍
